# This is a workflow to build and deploy to Dev environment
name: Dev-Pipeline

on:
  push:
    branches: ["github_actions","develop"]

  workflow_dispatch:
    inputs:
      build_healthchecks:
        description: "Build healthchecks ?"
        required: true
        default: "false"
        type: choice
        options:
          - true
          - false

      deploy_healthchecks:
        description: "Deploy healthchecks ?"
        required: true
        default: "false"
        type: choice
        options:
          - true
          - false

      healthchecks_version:
        description: "Provide only available versions ?"
        required: false
        type: string

jobs:

  repo-name:
    uses: kaleyra/kio-infra-dev/.github/workflows/repo-name.yml@master
    if: always()

  changes:
    name: Find changed paths
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    outputs:
      healthchecks: ${{ steps.filter.outputs.healthchecks }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Path filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            healthchecks:
              - '**'
              - '!.github/**'
              - '!doc/**'

  build-healthchecks:
    name: Build healthchecks Image
    needs: [repo-name, changes]
    if: ((needs.changes.outputs.healthchecks == 'true' && github.event_name != 'workflow_dispatch') || (github.event_name == 'workflow_dispatch' && github.event.inputs.build_healthchecks == 'true')) && !(failure() || cancelled())
    uses: kaleyra/kio-infra-dev/.github/workflows/build-images.yml@master
    secrets: inherit
    with:
      image_name: ghcr.io/${{ needs.repo-name.outputs.repo-name }}:${{ github.run_number }}
      platforms: linux/amd64
      include_token_arg: true

  deploy-healthchecks:
    name: Deploy healthchecks service
    needs: [repo-name, changes, build-healthchecks]
    if: ((needs.changes.outputs.healthchecks == 'true' && github.event_name != 'workflow_dispatch') || (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_healthchecks == 'true')) && !(failure() || cancelled())
    uses: kaleyra/kio-infra-dev/.github/workflows/deploy-eks.yml@master
    secrets: inherit
    with:
      image_name: ghcr.io/${{ needs.repo-name.outputs.repo-name }}
      image_version: ${{ github.event.inputs.healthchecks_version }}
      manifest_path: mumbai-region/apps/voice/healthchecks/overlays/default
      manifest_repo: kaleyra/kio-infra-dev
